### ISSUE TITLE
Download (customized) generates corrupt  css

### ISSUE THREAD

**Issue by a-kla** [Rezi/sugar-css#3]
Hello!

If I download the CSS i get a incomplete file.
I din't test it but i believe it's easy to fix:  just change the imports to `…?raw`.

`import CSSvariables from '$lib/scss/variables.scss?inline';`  => `import CSSvariables from '$lib/scss/variables.scss?raw';` 

I also noticed a `@charset "UTF-8";` in the middle of the file.

Btw: You can remove sass from your dependencies. You don't make use of it and you will not need Sass + Postcss.
You may take a look at https://github.com/Scrum/postcss-at-rules-variables .

**Comment by Rezi** [comment]
Works now again, reported issues are fixed.
